//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GableTest.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class bill_t_test
    {
        public int BILL_T_TEST_ID { get; set; }
        public string EMP_T_TEST_NAME { get; set; }
        public Nullable<int> EMP_T_TEST_ID { get; set; }
        public Nullable<int> TYPE_M_TEST_ID { get; set; }
        public Nullable<int> STAT_M_TEST_ID { get; set; }
        public Nullable<int> BILL_T_TES_VALUES { get; set; }
        public Nullable<System.DateTime> BILL_T_TEST_DATE { get; set; }
        public Nullable<System.DateTime> BILL_T_TEST_TIMESTMP { get; set; }
        public string BILL_T_TEST_ACTINE { get; set; }
        public Nullable<int> BILL_T_TEST_APPROVE_IDNAME { get; set; }
    }
}
