//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GableTest.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class emp_t_test
    {
        public int EMP_T_TEST_ID { get; set; }
        public Nullable<int> POSI_M_TEST_ID { get; set; }
        public string EMP_T_TEST_NAME { get; set; }
        public string EMP_T_TEST_SURNAME { get; set; }
        public string EMP_T_TEST_TELL { get; set; }
        public string EMP_T_TEST_EMAIL { get; set; }
        public string EMP_T_TEST_ACTIVE { get; set; }
    }
}
