//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GableTest.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gable_testEntities : DbContext
    {
        public gable_testEntities()
            : base("name=gable_testEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bill_t_test> bill_t_test { get; set; }
        public virtual DbSet<emp_t_test> emp_t_test { get; set; }
        public virtual DbSet<posi_m_test> posi_m_test { get; set; }
        public virtual DbSet<stat_m_test> stat_m_test { get; set; }
        public virtual DbSet<type_m_test> type_m_test { get; set; }
    }
}
