//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GableTest.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class posi_m_test
    {
        public int POSI_M_TEST_ID { get; set; }
        public string POSI_M_TEST_NAME { get; set; }
        public Nullable<System.DateTime> POSI_M_TEST_TIMESTMP { get; set; }
        public string POSI_M_TEST_ACTINE { get; set; }
    }
}
